### ISSUE TITLE
Investigate adding support for multiple *.csproj/*.fsproj files in the Paketo .NET Core Buildpack

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/dotnet-core#3]
Figure out if it is a realistic scenario and if so how to handle it. See https://docs.cloudfoundry.org/buildpacks/dotnet-core/index.html#multiple-projects for how this scenario is handled by the CF .NET Core Buildpack

**Comment by kvedurmu** [comment]
@ForestEckhardt could you add more context to this?

**Comment by ForestEckhardt** [comment]
This is done with the following settings in `buildpack.yml`.
```yaml
dotnet-build:                                                                                                                                                 
  project-path: "src/asp_web_app"
```
You can see an example app in the [here](https://github.com/paketo-buildpacks/dotnet-core-build/tree/master/integration/testdata/multiple_projects_msbuild).
