### ISSUE TITLE
Self-nomination as Dotnet Core contributor

### ISSUE THREAD

**Issue by floragj** [paketo-buildpacks/dotnet-core#344]
In keeping with [the Paketo Buildpacks Governance document](https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md), I am self-nominating as a contributor to the Dotnet Core language family.

I have recently contributed to the dotnet core rearchitecture in PRs that [rewrote the ICU buildpack with packit](https://github.com/paketo-buildpacks/icu/pull/70) and [rewrote the dotnet-publish buildpack with packit](https://github.com/paketo-buildpacks/dotnet-publish/pull/88).

**Comment by ForestEckhardt** [comment]
@joshzarrabi ^

**Comment by joshzarrabi** [comment]
Wooooo!

**Comment by ForestEckhardt** [comment]
It appears that a super majority of maintainers have approved. Congrats!
