### ISSUE TITLE
Allow Roll Forward behavior to be disabled

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/dotnet-core#385]
## What happened?

* What were you attempting to do?
I was trying to use a very specific version of .Net Core runtime. When I built my app, it chose a patch version that was newer than what I had specified.

* What did you expect to happen?
I have disabled roll forward by setting the `DOTNET_ROLL_FORWARD` to `Disable` as outlined in https://github.com/dotnet/designs/blob/main/accepted/2019/runtime-binding.md#rollforward. I expected the buildpack to use the versions I had specified.

* What was the actual behavior? Please provide log output, if possible.
It rolled forward to a newer patch version.

**Comment by joshuatcasey** [comment]
I'll take this!

**Comment by joshuatcasey** [comment]
I've got a PR here: https://github.com/paketo-buildpacks/dotnet-core-runtime/pull/304

But are we sure this behavior is desirable? Given the limited number of versions available in https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/main/buildpack.toml, when a developer selects a particular version and sets `DOTNET_ROLL_FORWARD=Disable` the chosen patch version may not be available for too long.

**Comment by sophiewigmore** [comment]
@joshuatcasey yes, this feature limits version availability, but it's not a default behaviour that someone would run into unless they were *very* sure of the version they want to use.
