### ISSUE TITLE
Inconsistent Buildpack Names

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-core#399]
## What happened?

* What were you attempting to do?

`Pack build` a Dotnet Core App and looking at the log output

* What did you expect to happen?

See nice, uniform logs with the different Dotnet Core buildpacks listed

* What was the actual behavior? Please provide log output, if possible.

The buildpack names are very inconsistent:

```
[builder]Paketo .NET Core Runtime Buildpack 0.0.201
...
[builder] Paketo ASP.Net Core Buildpack 0.0.196
...
[builder]  Paketo .NET SDK Buildpack 0.0.196
...
[builder] Paketo .Net Publish Buildpack 0.0.121
...
[builder] Paketo .NET Execute Buildpack 0.0.180
```

Half of the buildpacks have ".NET" (in all capitals), and some have ".Net". This isn't a huge issue, but it would be nice if the logs/names were consistent across the language family.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
 
packpack 

* What buildpacks are you using? Please include versions.

dotnet-core buildpack v0.0.9

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

https://github.com/paketo-buildpacks/dotnet-core/tree/main/integration/testdata/react-app

## Checklist

* [X] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by ryanmoran** [comment]
Its also worth noting that `runtime` and `aspnet` use "Core" while the `sdk` buildpack does not. Should all 3 of those be `Paketo .Net Core <something> Buildpack`?

**Comment by sophiewigmore** [comment]
@ryanmoran Yes, agreed

**Comment by ForestEckhardt** [comment]
I believe this had been completed with the above commits.
