### ISSUE TITLE
Self-nomination as a Dotnet Core Maintainer

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-core#416]
In keeping with the Paketo Buildpacks Governance document, I am self-nominating myself as a maintainer to the Paketo Dotnet Core language family.

I have contributed to many facets of the .NET Core re-architecture work and associated issues. A few things I have worked on:
[Inconsistent buildpack naming](https://github.com/paketo-buildpacks/dotnet-core/issues/399)
https://github.com/paketo-buildpacks/dotnet-publish/issues/87 via  a [.NET Publish PR](https://github.com/paketo-buildpacks/dotnet-publish/pull/107) and [.NET Execute PR](https://github.com/paketo-buildpacks/dotnet-execute/pull/100)
[.NET Core Runtime rewrite](https://github.com/paketo-buildpacks/dotnet-core-runtime/pull/110)
[.NET Execute rewrite](https://github.com/paketo-buildpacks/dotnet-execute/pull/80)

I believe this work shows a solid understanding of how the buildpacks across the language family work, and a vested interested in new changes to the buildpack.

**Comment by ForestEckhardt** [comment]
@joshzarrabi If you could take a look at this that would be great!

**Comment by ForestEckhardt** [comment]
Opened #423 to align with governance.
