### ISSUE TITLE
@sophiewigmore Maintainer Nomination

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/dotnet-core#423]
In keeping with the Paketo Buildpacks Governance document, I am nominating @sophiewigmore as a maintainer to the Paketo Dotnet Core language family.

Sophie has contributed to many facets of the .NET Core re-architecture work and associated issues. A few things she has worked on:
[Inconsistent buildpack naming](https://github.com/paketo-buildpacks/dotnet-core/issues/399)
https://github.com/paketo-buildpacks/dotnet-publish/issues/87 via  a [.NET Publish PR](https://github.com/paketo-buildpacks/dotnet-publish/pull/107) and [.NET Execute PR](https://github.com/paketo-buildpacks/dotnet-execute/pull/100)
[.NET Core Runtime rewrite](https://github.com/paketo-buildpacks/dotnet-core-runtime/pull/110)
[.NET Execute rewrite](https://github.com/paketo-buildpacks/dotnet-execute/pull/80)

I believe this work shows a solid understanding of how the buildpacks across the language family work, and a vested interested in new changes to the buildpack.

**Comment by joshzarrabi** [comment]
I approve! cc @ForestEckhardt @sophiewigmore

**Comment by fg-j** [comment]
I approve!
