### ISSUE TITLE
Add top level [[buildpack.licenses]] field

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/dotnet-core#429]
## What happened?
We should add the top level `[[buildpack.licenses]]` field to `buildpack.toml` (and all implementation buildpacks) so users can see the buildpack's license through an app image's bill of materials.

**Comment by fg-j** [comment]
Implementing this would bring us in line with [this accepted upstream RFC](https://github.com/buildpacks/rfcs/blob/main/text/0070-new-buildpack-toml-keys.md). Metadata in that field will be added to image metadata as of [pack v0.17.0](https://github.com/buildpacks/pack/commit/5eb3093c22db499416a33c3c6c82e6b9801cd1db).

**Comment by fg-j** [comment]
Repos that need a license field added:
- [x] paketo-buildpacks/dotnet-core-sdk
- [x] paketo-buildpacks/dotnet-core-runtime
- [x] paketo-buildpacks/dotnet-core-aspnet
- [x] https://github.com/paketo-buildpacks/dotnet-publish
- [x] https://github.com/paketo-buildpacks/dotnet-execute
- [x] icu
- [x] node-engine
- [x] procfile
- [x] environment-variables
- [x] image-labels
- [x] ca-certificates
- [x] watchexec

**Comment by sophiewigmore** [comment]
@fg-j I believe all of the .NET buildpacks above are now on Buildpack API 0.6, so this issue is no longer blocked!
