### ISSUE TITLE
Update .NET Website Docs with bp.yaml migration information

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-core#456]
Following the completion of the following issues: 
https://github.com/paketo-buildpacks/dotnet-core-runtime/issues/150
https://github.com/paketo-buildpacks/dotnet-core-aspnet/issues/151
https://github.com/paketo-buildpacks/dotnet-core-sdk/issues/152

We should update the .NET Core Buildpack docs on the Paketo website to include information about how to use the related environment variables and migrate away from using buildpack.yml. See [Node.js docs](https://paketo.io/docs/buildpacks/language-family-buildpacks/nodejs/#using-bp_node_version) as an example.

**Comment by sophiewigmore** [comment]
Blocked on issues in description getting resolved.

**Comment by sophiewigmore** [comment]
Waiting for resolution to paketo-buildpacks/dotnet-core-sdk#152 to close this out

**Comment by fg-j** [comment]
Docs are updated in #475
