### ISSUE TITLE
Implement RFC 0002 buildpack.yml to env. var

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-core#466]
Implementation of https://github.com/paketo-buildpacks/dotnet-core/blob/main/rfcs/0002-buildpack-yml-to-env-var.md is in progress. This issue should get closed when all related issues are closed:

https://github.com/paketo-buildpacks/dotnet-publish/issues/154
https://github.com/paketo-buildpacks/dotnet-core-sdk/issues/152
https://github.com/paketo-buildpacks/dotnet-core-aspnet/issues/151
https://github.com/paketo-buildpacks/dotnet-core-runtime/issues/150
https://github.com/paketo-buildpacks/dotnet-core/issues/456
https://github.com/paketo-buildpacks/dotnet-core-sdk/issues/170
https://github.com/paketo-buildpacks/dotnet-execute/issues/151

**Comment by thangchung** [comment]
@sophiewigmore I have seen almost all PRs above were resolved so when this PR will be resolved too?

**Comment by fg-j** [comment]
@thangchung -- we're hoping to cut a language family release with this by the end of the week!

**Comment by fg-j** [comment]
Environment variable configuration has been released in [v0.2.0](https://github.com/paketo-buildpacks/dotnet-core/releases/tag/v0.2.0).
