### ISSUE TITLE
Configure Verbosity and other command line arguments

### ISSUE THREAD

**Issue by tsfrt** [paketo-buildpacks/dotnet-core#501]
## What happened?
This could be my own ignorance, but is there a way to configure the verbosity of the dotnet cli when building images?  It can be difficult to understand what is going within the buildpack.

* What were you attempting to do?
Get detailed verbosity from buildpack output.

* What did you expect to happen?
Expected to be able to pass `-v d` or set and environment variable to increase the detail of dotnet build time logging.

* What was the actual behavior? Please provide log output, if possible.

## Build Configuration
Simple dotnet core api project build

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
kpack  0.2.2-rc.1
* What buildpacks are you using? Please include versions.
tanzu-buildpacks/dotnet-core@0.0.7        

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by tsfrt** [comment]
I ran into another issue which bumps into a similar limitation.  I want to be able to specify command line arguments like a `dotnet restore -s <NuGet feed>`.  With other buildpacks, like Gradle for instance, I can basically control the command line invocation.

**Comment by fg-j** [comment]
Thanks for bringing this to our attention @tsfrt . This seems related to https://github.com/paketo-buildpacks/dotnet-publish/issues/145, too.

To avoid tightly coupling the buildpack environment variable configuration to the [available configuration options for `dotnet publish`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish), a reasonable approach might be a `BP_DOTNET_FLAGS` environment variable that allows the user to pass arbitrary flags to the dotnet CLI. Would that help you @tsfrt ?

On a separate note, the current implementation of the buildpack [only reveals the output logged by `dotnet publish` if the command fails](https://github.com/paketo-buildpacks/dotnet-publish/blob/202a1b4b63b571d1c8ae7c842c521e10f4e8e2c9/dotnet_publish_process.go#L54-L59). Is that sufficient for your use-case, or would you like to see verbose output even when the command succeeds?

**Comment by tsfrt** [comment]
BP_DOTNET_FLAGS makes sense to me

At least log failures in more detail, although I could imagine a case where things are working just not the way you expect where detailed output might reveal something in successful builds too?  I am not as versed with dotnet development, so you may want to get more input on that.

**Comment by fg-j** [comment]
As of [.NET Core Buildpack v0.9.0](https://github.com/paketo-buildpacks/dotnet-core/releases/tag/v0.9.0), Command line arguments can now be passed to the dotnet CLI using `BP_DOTNET_PUBLISH_FLAGS`. See [the Paketo documentation](https://paketo.io/docs/howto/dotnet-core/#configure-the-dotnet-publish-command) for more details.
