### ISSUE TITLE
Add Procfile to group order

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/dotnet-core#6]
We should add the Procfile Paketo Buildpack to the .NET Core Language family buildpack so that users can define start commands via a Procfile (see paketo-buildpacks/rfcs#7)

**Comment by fg-j** [comment]
It looks like the integration tests use Procfile to set a start command that's identical to the start command the Dotnet Execute buildpack would set:

From [Dotnet execute](https://github.com/paketo-buildpacks/dotnet-execute/blob/66666e5c395b9e16fbb247c0f2b40dc6c9af839c/build.go#L31)
```
command := fmt.Sprintf("%s --urls http://0.0.0.0:${PORT:-8080}", filepath.Join(builtAppPath, config.AppName))
```

From [language family integration tests](https://github.com/paketo-buildpacks/dotnet-core/blob/ed200906dc8c9ca0de80881944264a4f83474d18/integration/source_test.go#L96):
```
Expect(ioutil.WriteFile(filepath.Join(source, "Procfile"), []byte("web: /workspace/react-app --urls http://0.0.0.0:${PORT:-8080}"), 0644)).To(Succeed())
```

It might be nice if the Procfile sets a start command that is slightly different (e.g. pre-append some useless command) so we have evidence that the Procfile actually updates the start command.
