### ISSUE TITLE
Optimize layering to maximize docker layer cache hits

### ISSUE THREAD

**Issue by macsux** [paketo-buildpacks/dotnet-core#610]
Currently when buildpack is run, the output of `dotnet publish` is added a single layer to the container. The output of publish folder will have a mix of direct project code assemblies and dependent libraries. While application dependencies rarely change between builds, putting application code and dependencies into a single layer fails to capitalize on docker's cache reuse. For example a project with many dependencies, changing one line of code will often produce a new 30MB+ layer that takes up valuable storage and would need to be sent across the wire, even though the actual delta maybe less than 1MB. 

Proposal is utilize logic found in my library NMica to split publish output across multiple layers, maximizing cache reuse across builds. This can be done by analyzing `project.assets.json` file in `obj` folder to figure out which assemblies are imported as dependencies and which are projects. 

Such optimization is especially beneficial when working with tilt. 

Full details on the problem and how NMica works can be found in this blog post https://stakhov.pro/building-efficient-net-docker-images/

Core of the logic that would need to be implemented is here:
https://github.com/NMica/NMica/blob/master/src/NMica/Tasks/PublishLayer.cs

**Comment by fg-j** [comment]
Hi @macsux. Just took a look at the blog post you linked.
While it is true that "Currently when buildpack is run, the output of `dotnet publish` is added a single layer to the container,", as far as I can tell, this fact doesn't _quite_ cause the same problems in the CNB world that it causes with Dockerfiles, since CNB has more sophisticated layer caching mechanisms than Dockerfile.

Is there a performance issue with the .NET Core buildpack that you think your tool would address? If so, can you be more specific about which part(s) of the build process are currently slow, and how your tool would speed them up?

**Comment by macsux** [comment]
> this fact doesn't quite cause the same problems in the CNB world that it causes with Dockerfiles, since CNB has more sophisticated layer caching mechanisms than Dockerfile.

The buildpack does absolutely nothing to improve on status quo in this case because you're still combining project's own code with any nuget dependencies (or dependent project references) into a single layer. While you have dotnet runtime as a seperate layer, this is no different than Dockerfile where you inherit from one of Microsoft's official base .net images that already have the framework in the upper layers. 

My solution splits up the output of `publish` into 4 distinct layers, ordered based on their likelyhood of change:

package – any NuGet package references your app depends upon (least likely to change between builds)
earlypackage – NuGet packages that are considered pre-release. As these are more likely to be updated, this helps us isolate them into a separate layer
project – any projects that your main entry point project depends on
app – your main code and anything that doesn’t fit in the above category (most likely to change between builds)

You then create 4 layers instead of 1 from what comes out from `publish` command, maximizing cache hits.

Please [read the blog post I linked as it explains the problem and solution in detail](https://stakhov.pro/building-efficient-net-docker-images/). 

Just to note, this [idea is actually taken from Java Spring](https://redamessoudi.com/optimized-docker-images-for-spring-boot-apps/) and I've reimplemented it for .NET in a form of NMica project. IDK if the java buildpack leverages this feature though. The only way to determine that is to look at relationship if inputs into the build system and the outputs in publish folder. This relationship is established by MSBuild and can be read by analyzing `project.assets.json` file obj folder.

My own testing has shown that for realistic projects that have dependencies beyond just on BCL libraries of .NET runtime itself, the optimization can be upwards of 90% in image size between builds. This is accomplished mainly by not sending all the dlls that came from dependent nuget packages that haven't changed between builds, because they are isolated in their own layer and you get a cache hit. This translates into faster pushes across the wire and less disk consumption, so it's absolutely worth investing in.

**Comment by ForestEckhardt** [comment]
Forgive my ignorance for a second here because I am not super familiar with the guts of `publish`. I think I understand the potential image upload advantage by slicing the cache like this (we are only uploading new layers that have changed). It would seem to me however that I still need `publish` the app and then evaluate the checksums on the layers to see if we can reuse any of the layers. Is this the case? If so, I think that this is still valuable optimization but it does inform how I wrap my head around actually doing the implementation, so if I could some clarity on this that would be great!

**Comment by macsux** [comment]
I'm not super familiar with how container layers do caching, as I've only worked with it via docker. I know pack doesn't use docker, so I can't speak as to whether layer caching is automatic or something extra you have to do with whatever lib you're using to construct images. 

I'll speak as if we were doing this in docker:
The lib I made will spit out something that normally ends up in a *flat* `publish` folder into 4 distinct subfolders. We then put 4 instructions into dockerfile like this:

```Dockerfile
COPY --from=build /layer/package ./
COPY --from=build /layer/earlypackage ./
COPY --from=build /layer/project ./
COPY --from=build /layer/app ./
```

At the end of each instruction, docker will check if the resulting layer already exists via checksum, and if it does will reuse existing layer instead of minting new one. So the "split" into folders is actually only temporary, as they get merged back into single folder in the run image, but across 4 distinct layers.

If you're asking HOW to implement what the lib does (without using lib itself), the key logic is found [here](https://github.com/NMica/NMica/blob/master/src/NMica/Tasks/PublishLayer.cs).

**Comment by sophiewigmore** [comment]
Per @ryanmoran - The CNB concept of `slices` might come in handy, which functions as an array of paths that the
 lifecycle can export these slices as individual layers. If the slice hasn't changed, the lifecycle should be able to tell.
