### ISSUE TITLE
Support configuring NuGet via service bindings

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/dotnet-core#618]
Its somewhat common to need to configure NuGet with some credentials. We can enable this more fluently by allowing users to pass a `nuget.config` file via a service binding into the build context.

This buildpack should consider adding this support in the necessary location to support this type of workflow.

**Comment by fg-j** [comment]
Ideally, adding a `nuget.config` to the build environment shouldn't override any `nuget.config` that's already present in the app directory. We should identify the location in the container where NuGet will look for a "global" NuGet config.

**Comment by sophiewigmore** [comment]
Included in https://github.com/paketo-buildpacks/dotnet-core/releases/tag/v0.11.0
