### ISSUE TITLE
.NET Core 3.1 End of Life: December 13 2022

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/dotnet-core#810]
.NET Core 3.1 is the oldest supported LTS version of .NET Core. It's [going out of support](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) on December 13 2022. Typically, Paketo buildpacks do not maintain dependency version lines beyond when they are supported upstream. So, .NET 3.1 should be removed from the buildpack in a release soon after the EOL date.

**Comment by ForestEckhardt** [comment]
.Net 3.1 has been removed!
