### ISSUE TITLE
Investigating supporting .NET Core 8

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-core#978]
[.NET Core 8](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8) will be released officially in November 2023 (according to the [Microsoft Release Cadence](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#cadence) document). We should investigate what features are changing from .NET 7 to 8, and file issues for any breaking changes that will require fixes in the buildpacks in order to support .NET Core 8.

**Comment by sophiewigmore** [comment]
Additional context from @timhess, .NET 8 RC1 is considered a "Go-Live" release, meaning it is supported in production now. This prob means we can move up our timeline on working on this

**Comment by ForestEckhardt** [comment]
https://github.com/paketo-buildpacks/dotnet-core/releases/tag/v0.42.0
